# Generated by Django 4.2 on 2025-04-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chambermarie', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('chambermarie_image', models.ImageField(blank=True, null=True, upload_to='venues/chambermarie/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=20)),
                ('is_beach', models.BooleanField(default=False)),
                ('is_city', models.BooleanField(default=False)),
                ('is_hotel', models.BooleanField(default=False)),
                ('is_countryside', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(upload_to='venues/thumbnails/')),
                ('full_address', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Connecticut', 'Connecticut'), ('New York', 'New York'), ('Los Angeles', 'Los Angeles'), ('California', 'California')], max_length=100)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_prayer_rooms', models.BooleanField(default=False)),
                ('has_dj', models.BooleanField(default=False)),
                ('has_photographer', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/gallery/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.venue')),
            ],
        ),
    ]
