# Generated by Django 4.2 on 2025-04-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_venue_created_by_venue_status_venue_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='Active', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_gallery/'),
        ),
    ]
