# Generated by Django 3.2.12 on 2025-04-11 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_venue_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
    ]
