# Generated by Django 3.2.12 on 2025-04-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_venue_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('Morning (9 AM - 12 PM)', 'Morning (9 AM - 12 PM)'), ('Afternoon (12 PM - 3 PM)', 'Afternoon (12 PM - 3 PM)'), ('Evening (3 PM - 6 PM)', 'Evening (3 PM - 6 PM)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
