# Generated by Django 4.2 on 2025-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
