# Generated by Django 3.2.12 on 2025-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_visitrequest_venue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='venue_id',
            field=models.IntegerField(default=1),
        ),
    ]
