# Generated by Django 3.2.12 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20250414_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue_id',
            field=models.IntegerField(default=1),
        ),
    ]
