# Generated by Django 3.2.12 on 2025-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_forest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_mountain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_resort',
            field=models.BooleanField(default=False),
        ),
    ]
