# Generated by Django 3.2.12 on 2025-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20250418_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_rooftop',
            field=models.BooleanField(default=False),
        ),
    ]
