# Generated by Django 3.2.12 on 2025-04-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_venue_is_rooftop'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_garden',
            field=models.BooleanField(default=False),
        ),
    ]
