# Generated by Django 4.2 on 2025-04-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_visitrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_cave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_desert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_island',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_lake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_vineyard',
            field=models.BooleanField(default=False),
        ),
    ]
