# Generated by Django 4.2 on 2025-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_venue_is_cave_venue_is_desert_venue_is_island_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
