# Generated by Django 4.2 on 2025-04-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_venue_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.venue'),
        ),
    ]
