# Generated by Django 4.2 on 2025-04-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_booking_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitrequest',
            name='venue_id',
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.venue'),
        ),
    ]
